### PR TITLE
Change more places to colsql

### PR DESCRIPTION
**Pull request by hw202207**

### CODE REVIEW

**Review by hlissner — APPROVED** [review]

**Comment by hlissner** [comment]
Sorry for the wait. This PR slipped under my radar. Thanks for the help!

**Comment by tarsius** [comment]
This is a very bad pull-request, and because there was no justification given for why the contributor concluded this was the right thing to do, it should not have been merged. (Not meant as a criticism, of course I understand that mistakes can happen, when one has to review as many pull-requests as you do.)

As is evident from the metastasized typo, the contributor performed zero testing. Unfortunately fixing the typo does not actually change anything. The functions `closql`, `closql-live-p` and `closql-close` do not exist, and never have. The `emacsql*` functions, which this pr replaced, continue to exist.

While it looks correct, more work *might* be needed on top of #1, to make this package compatible with the latest `emacsql`, `closql` and `forge`, but this pull-request certainly isn't it. (I don't know, I don't use this package.)

Re https://github.com/wandersoncferreira/code-review/issues/245 https://github.com/wandersoncferreira/code-review/issues/246 https://github.com/magit/emacsql/issues/113.

**Comment by hlissner** [comment]
Agreed. Unfortunately, I don't use `code-review` either, so I took the PR at face value. I'm open to PRs if someone more knowledgeable is willing to bridge that gap.

**Comment by tarsius** [comment]
Well in https://github.com/wandersoncferreira/code-review/pull/246 a few people said, that was merged here as #1, fixed the issue for them. So why not just revert this (and the fixup), to go back to that state?

**Comment by hlissner** [comment]
Oh, wasn't sure that was all it needed. Alright, will do!

**Pull request merged**
